"""initial account identity and sync permissions

Revision ID: 9f8c816cc317
Revises:
Create Date: 2026-09-28 11:00:40.297373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8c816cc317'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.String(length=48), nullable=False),
    sa.Column('client_secret', sa.String(length=120), nullable=True),
    sa.Column('client_id_issued_at', sa.Integer(), nullable=False),
    sa.Column('client_secret_expires_at', sa.Integer(), nullable=False),
    sa.Column('client_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client')),
    sa.UniqueConstraint('client_id', name=op.f('uq_client_client_id')),
    sa.UniqueConstraint('slug', name=op.f('uq_client_slug'))
    )
    op.create_table('rate_bucket',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('starts_at', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_rate_bucket'))
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('totp_secret', sa.Text(), nullable=True),
    sa.Column('totp_last_counter', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('browser_session',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.Integer(), nullable=False),
    sa.Column('authenticated_at', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('user_agent', sa.String(length=240), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_browser_session_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_browser_session'))
    )
    with op.batch_alter_table('browser_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_browser_session_user_id'), ['user_id'], unique=False)

    op.create_table('challenge',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('browser_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_challenge_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenge'))
    )
    op.create_table('cloud_connection',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=254), nullable=False),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.Column('connected_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_cloud_connection_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_cloud_connection'))
    )
    op.create_table('consent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=48), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], name=op.f('fk_consent_client_id_client'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_consent_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent')),
    sa.UniqueConstraint('user_id', 'client_id', name=op.f('uq_consent_user_id'))
    )
    op.create_table('discord_identity',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('linked_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_discord_identity_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discord_identity')),
    sa.UniqueConstraint('user_id', name=op.f('uq_discord_identity_user_id'))
    )
    op.create_table('mail_action',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_mail_action_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mail_action'))
    )
    with op.batch_alter_table('mail_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mail_action_user_id'), ['user_id'], unique=False)

    op.create_table('passkey',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.Text(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_passkey_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passkey')),
    sa.UniqueConstraint('credential_id', name=op.f('uq_passkey_credential_id'))
    )
    with op.batch_alter_table('passkey', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passkey_user_id'), ['user_id'], unique=False)

    op.create_table('recovery_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_recovery_code_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_code')),
    sa.UniqueConstraint('code_hash', name=op.f('uq_recovery_code_code_hash'))
    )
    with op.batch_alter_table('recovery_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_code_user_id'), ['user_id'], unique=False)

    op.create_table('sync_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('app_slug', sa.String(length=40), nullable=False),
    sa.Column('resource', sa.String(length=60), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_sync', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_sync_preference_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_preference')),
    sa.UniqueConstraint('user_id', 'app_slug', 'resource', name=op.f('uq_sync_preference_user_id'))
    )
    op.create_table('authorization_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('client_id', sa.String(length=48), nullable=True),
    sa.Column('redirect_uri', sa.Text(), nullable=True),
    sa.Column('response_type', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('nonce', sa.Text(), nullable=True),
    sa.Column('auth_time', sa.Integer(), nullable=False),
    sa.Column('acr', sa.Text(), nullable=True),
    sa.Column('amr', sa.Text(), nullable=True),
    sa.Column('code_challenge', sa.Text(), nullable=True),
    sa.Column('code_challenge_method', sa.String(length=48), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['browser_session.id'], name=op.f('fk_authorization_code_session_id_browser_session'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_authorization_code_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authorization_code')),
    sa.UniqueConstraint('code', name=op.f('uq_authorization_code_code'))
    )
    op.create_table('o_auth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('family', sa.String(length=36), nullable=False),
    sa.Column('access_hash', sa.String(length=64), nullable=False),
    sa.Column('refresh_hash', sa.String(length=64), nullable=True),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.Integer(), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('refresh_expires_at', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('refresh_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], name=op.f('fk_o_auth_token_client_id_client'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['code_id'], ['authorization_code.id'], name=op.f('fk_o_auth_token_code_id_authorization_code'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['browser_session.id'], name=op.f('fk_o_auth_token_session_id_browser_session'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_o_auth_token_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_o_auth_token')),
    sa.UniqueConstraint('access_hash', name=op.f('uq_o_auth_token_access_hash')),
    sa.UniqueConstraint('refresh_hash', name=op.f('uq_o_auth_token_refresh_hash'))
    )
    with op.batch_alter_table('o_auth_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_o_auth_token_family'), ['family'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('o_auth_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_o_auth_token_family'))

    op.drop_table('o_auth_token')
    op.drop_table('authorization_code')
    op.drop_table('sync_preference')
    with op.batch_alter_table('recovery_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_code_user_id'))

    op.drop_table('recovery_code')
    with op.batch_alter_table('passkey', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passkey_user_id'))

    op.drop_table('passkey')
    with op.batch_alter_table('mail_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mail_action_user_id'))

    op.drop_table('mail_action')
    op.drop_table('discord_identity')
    op.drop_table('consent')
    op.drop_table('cloud_connection')
    op.drop_table('challenge')
    with op.batch_alter_table('browser_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_browser_session_user_id'))

    op.drop_table('browser_session')
    op.drop_table('user')
    op.drop_table('rate_bucket')
    op.drop_table('client')
    # ### end Alembic commands ###
